### ISSUE TITLE
Place holder: Accordion on persons page for influenced by this person (from 1141)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#51] opened 2024-02-22 16:59 UTC
**Problem Description:**
Note: Place Holder for Front End - Content is copied over from Front End Ticket. 

Currently we can only search for objects created by artists  rather than ...
- creations that were influenced by an artist
- designers 
- other types of creators (unsure of what other types that would be)

**Expected Behavior/Solution:**
To be able to search for more than one creator, but not specific names. Possibly a count. 

**Requirements:**

- [ ] New accordion on the persons page (name: objects influenced by this person)  

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Heather
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- [Influenced by Joseph Wright of Derby](https://lux.collections.yale.edu/view/object/536a5eb6-bb68-439c-b199-b0e9d9f531ae)
- [Joseph Wright of Derby Search Results](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22joseph%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22wright%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22of%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22derby%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=joseph+wright+of+derby&is=anySortName%3Adesc&ip=2)

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**
- https://www.bugherd.com/projects/284041/tasks/1925
- [Location in lux](https://lux-front-tst.collections.yale.edu/view/results/objects?q= )
- 

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by roamye** [comment] 2024-03-13 13:36
From the old ticket - this was originally made in the wrong repo. the content was supposed to be in a front end issue not a mark logic one. This mark logic ticket will serve as a placeholder if one is needed for the front end issue: https://github.com/project-lux/lux-frontend/issues/82

If it is not needed, it can be closed.

**Comment by roamye** [comment] 2024-03-13 19:47
Dupe of: https://github.com/project-lux/lux-middletier/issues/27. Closing

**Closed by roamye** 2024-03-13 19:47 UTC
Labels: Forming, normal, Accordion
