### ISSUE TITLE
Research: Tab results do not appear when "&" is used in a simple search. 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-marklogic#111] opened 2024-04-26 20:16 UTC
**Problem Description:**
Lux is supposed to ignore punctuation when a user submits a search. However, when a user uses the '&' in a simple search an error will occur where the results in each scope are non existent. This issue serves as a research ticket to figure out why this bug happens and what a potential solution could be. 

**Expected Behavior/Solution:**
Research issue on why this happens and what a possible solution could be. 

**Requirements:**
TBD based on proposed solution. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- [McKinsey & company](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22mckinsey%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22%26%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22company%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=mckinsey+%26+company)
- [English landscape 1630-1850: drawings, prints & books from the Paul Mellon collection](https://lux-front-tst.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22English%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22landscape%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%221630-1850%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22%3A%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22drawings%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22%2C%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22prints%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22%26%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22books%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22from%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22the%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22Paul%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22Mellon%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22collection%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=English%20landscape%201630-1850%3A%20drawings%2C%20prints%20%26%20books%20from%20the%20Paul%20Mellon%20collection) (tst) 

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**
- BugHerd: https://www.bugherd.com/projects/284041/tasks/2153

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by brent-hartwig** [comment] 2024-04-29 21:16
I can reproduce this by hitting the backend search endpoint directly.  While I do not have an explanation yet for the following yet, here is the associated error message:

> JS-JAVASCRIPT: throw new NotFoundError(\`Document '${uri}' Not Found\`); -- Error running JavaScript request: Error: Document 'https://lux.collections.yale.edu/data/user/login' Not Found\nin ./mlErrorsLib.mjs, at 26:4, in NotFoundError() [javascript]\nin ../../lib/crudLib.mjs, at 8:10, in get() [javascript]\nin /ds/lux/document.mjs, at 8:9 [javascript]\nin ../../lib/requestHandleLib.mjs, at 10:9, in handleRequest() [javascript]\nin /ds/lux/document.mjs, at 7:0 [javascript]\nin /ds/lux/document.mjs [javascript]

@clarkepeterf, do you know where https://lux.collections.yale.edu/data/user/login may be coming from?

**Comment by brent-hartwig** [comment] 2024-04-29 21:23
The following does not reproduce the error in DEV, at the time of this writing.

Endpoint: `/ds/lux/search.mjs`
`scope` parameter: `item`
`q` parameter: `{"text":"English landscape 1630-1850: drawings, prints & books from the Paul Mellon collection"}`

`totalItems` for the above search is 45.

**Comment by brent-hartwig** [comment] 2024-04-30 18:27
@kamerynB and @clarkepeterf, I suspect the issue has to do with encoding the search criteria in the frontend's calls to `/api/search-estimate/[scope]?q=[criteria]`, specifically when there is an ampersand in the search criteria.  If not encoded, `q` parameter value gets truncated and perhaps the middle tier is dropping the perceived query string parameter when passing the request onto the backend.

Take the search for `Japanese & American` for example.  The search URL is properly encoded:

https://lux.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22Japanese%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22%26%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22America%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=Japanese+%26+America

Whereas the search estimate requests are not:

https://lux.collections.yale.edu/api/search-estimate/item?q={%22AND%22:[{%22text%22:%22Japanese%22,%22_lang%22:%22en%22},{%22text%22:%22&%22,%22_lang%22:%22en%22},{%22text%22:%22America%22,%22_lang%22:%22en%22}]}

Arguably, the backend's translate endpoint should do this; however, the frontend must be doing something to make the search request work.  Please advise how you would like this addressed.  Thank you.

**Comment by clarkepeterf** [comment] 2024-04-30 18:36
@brent-hartwig Yes, looks like the frontend is properly encoding the URL for `search` but not for `search-estimates`. That should be fixed. But if punctuation is to be ignored, does that mean we should remove punctuation on the frontend before sending to ML? Or do we need to update the logic in ML to remove punctuation? I'd lean towards doing the removal of punctuation in ML

**Comment by brent-hartwig** [comment] 2024-04-30 18:43
@clarkepeterf, at present, the backend strips out punctuation-only search terms while converting the search criteria into the query, specifically [here](https://github.com/project-lux/lux-marklogic/blob/main/src/main/ml-modules/base/root/lib/SearchCriteriaProcessor.mjs#L600-L607).  We could refactor and have the translate endpoint also do this, but for backend consumers that do not go through the translate endpoint, we'll need to have the current base covered too.

**Comment by azaroth42** [comment] 2024-05-06 20:50
Boo! I have demo where the main culprit is "McKinsey & Company" :(

**Comment by brent-hartwig** [comment] 2024-05-06 21:02
@azaroth42, which environment would you need this fixed in before your demo?

@clarkepeterf or @kamerynB, based on Rob's answer, please consideration options on making the following edit, consulting  @prowns and @jffcamp as needed.  Thank you.

> Yes, looks like the frontend is properly encoding the URI components for search but not for search-estimate. That should be fixed.

**Comment by brent-hartwig** [comment] 2024-08-08 13:06
@kamerynB or @clarkepeterf, I'm wondering if we can close this backend ticket.  Did the cause turn out to be an encoding issue in the frontend for search-estimate and, if so, was it addressed?  

cc: @roamye

**Comment by kamerynB** [comment] 2024-08-08 18:07
@clarkepeterf @brent-hartwig When I test the encoded URI, it works just fine, as shown in the screenshot below. It is encoded by the `fetch` functionality in Javascript but it appears to process it without causing errors. I'm looking into the middle tier to see if something is going on there. You can see the example endpoint fails but it looks like the `q` param is encoded just fine.

I'm testing this endpoint:
https://lux-front-dev.collections.yale.edu/api/search-estimate/item?q={%22AND%22:[{%22text%22:%22McKinsey%22,%22_lang%22:%22en%22},{%22text%22:%22&%22,%22_lang%22:%22en%22},{%22text%22:%22Company%22,%22_lang%22:%22en%22}]}

**Comment by brent-hartwig** [comment] 2024-08-08 18:10
@kamerynB, something could have changed since April but my findings from then ([here](https://github.com/project-lux/lux-marklogic/issues/111#issuecomment-2086444857)) revealed the search estimate URLs leaving the frontend were mis-encoded.  I'll see if I can reproduce today, but feel free to call me off is this is a red herring.

**Comment by brent-hartwig** [comment] 2024-08-08 18:12
The findings from April are still true today, in DEV.

**Comment by kamerynB** [comment] 2024-08-08 18:28
@brent-hartwig It must be something with the `fetch` function then. I'm looking into it now. If you search for Rob's example of `McKinsey & Company` and then go to the advanced search, the estimates work. That single estimates request does not request the estimates using `fetch`. I will investigate more.

**Comment by kamerynB** [comment] 2024-08-08 19:53
@brent-hartwig @clarkepeterf When I hit the middletier directly with the following endpoints, the first one passes and the second one fails.

1. [search for "McKinsey Company"](https://lux-front-tst.collections.yale.edu/api/search-estimate/item?q={%22AND%22:[{%22text%22:%22McKinsey%22,%22_lang%22:%22en%22},{%22text%22:%22Company%22,%22_lang%22:%22en%22}]})
2. [search for "McKinsey & Company"](https://lux-front-tst.collections.yale.edu/api/search-estimate/item?q={%22AND%22:[{%22text%22:%22McKinsey%22,%22_lang%22:%22en%22},{%22text%22:%22&%22,%22_lang%22:%22en%22},{%22text%22:%22Company%22,%22_lang%22:%22en%22}]})

Now, these both appear to have the correct JSON formatting for the `q` param. I have also yet to find anything that says `fetch` encodes the data in any way and right now, I can't find anything that indicates the frontend is encoding the string before sending it. 

I'm calling it quits for today. I will pick this up again next week. I'm still thinking there is something going on in the middletier that I have yet to find.

**Comment by azaroth42** [comment] 2024-08-08 19:56
You need to percent encode the & so that it doesn't look like a new query parameter

**Comment by kamerynB** [comment] 2024-08-12 18:24
@brent-hartwig @azaroth42 @clarkepeterf I found the problem! It has to do with the URLSearchParams javascript object. In most cases, this object is being used to set the search parameters but it wasn't being implemented in estimates requests. I will create a frontend ticket and I propose this issue be closed.

**Comment by brent-hartwig** [comment] 2024-08-12 19:03
Sweet!  Thank you and closing!

**Closed by brent-hartwig** 2024-08-12 19:03 UTC
Labels: propose-close, research, bugherd
