### ISSUE TITLE
Create Data Constants For New Icons

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#59] opened 2024-02-27 19:22 UTC
**Problem Description:**
The frontend wants to add icons for different item types

May be affected by our new way of handling data constants:
https://github.com/project-lux/lux-marklogic/issues/54
**Expected Behavior/Solution:**
data constants are added for new item types
**Requirements:**
When the ticket is complete, data constants will exist for the following types:
[Collections](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22o%27keeffe%22%2C%22_lang%22%3A%22en%22%7D&sq=o%27keeffe&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F24a671f3-e269-4ad9-9710-4796b8cc9478%22%7D%7D%5D%7D&facetRequest=true)
[Software & Electronic Media](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22data%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22set%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=data+set&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2Fec279104-cf49-4c00-8dd8-caa5f307d777%22%7D%7D%5D%7D&facetRequest=true)
[Textual Works](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22o%27keeffe%22%2C%22_lang%22%3A%22en%22%7D&sq=o%27keeffe&ip=1&facetRequest=true&if=%7B%22AND%22%3A%5B%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F5162b925-3d52-4d50-928c-0594851308d9%22%7D%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F5162b925-3d52-4d50-928c-0594851308d9%22%7D%7D%7D%5D%7D%5D%7D)
[Scores and Notation](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22music%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22score%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=music+score)
[Objects](https://lux.collections.yale.edu/view/object/21f8cdf3-24ba-4a85-a0ad-7d030eb84550)
[Cartography](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22map%22%2C%22_lang%22%3A%22en%22%7D&sq=map&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F6e901924-9ff3-4056-a1ce-71dce5424b33%22%7D%7D%5D%7D&facetRequest=true)
[Numismatics](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22coin%22%2C%22_lang%22%3A%22en%22%7D&sq=coin&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2Faa806050-b45a-4e0c-9eab-5d396b711a77%22%7D%7D%5D%7D&facetRequest=true)
[Specimens](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22maple%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22leaf%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=maple+leaf&ip=1&facetRequest=true&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F05a41429-8a18-4911-854e-eae804b7d46f%22%7D%7D%5D%7D)
[Audio](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22box%22%2C%22_lang%22%3A%22en%22%7D&sq=box&ip=1&facetRequest=true&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F912de2b2-e751-4d25-9290-7e67a45ec34c%22%7D%7D%2C%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2Fb6cb6d82-3a56-443f-8826-139c201afd2a%22%7D%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2Fb6cb6d82-3a56-443f-8826-139c201afd2a%22%7D%7D%7D%5D%7D%5D%7D)
[Video](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22video%22%2C%22_lang%22%3A%22en%22%7D&sq=video&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2Facf2cace-57e0-4237-b9f9-6b6b5dc4c51c%22%7D%7D%5D%7D&facetRequest=true)
[Visual Works](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22o%27keeffe%22%2C%22_lang%22%3A%22en%22%7D&sq=o%27keeffe&ip=1&facetRequest=true&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F4a172143-a50e-4d91-a88b-a9931bceecf1%22%7D%7D%5D%7D)
[Clothing](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22robe%22%2C%22_lang%22%3A%22en%22%7D&sq=robe&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F9bca0cc3-3b2f-4020-ba8e-ec472cd3b03f%22%7D%7D%5D%7D&facetRequest=true)
[Journals & Newspapers](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22Washington%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22post%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=Washington+post&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F5ef5aa2a-669c-449e-8a32-5582c5f96514%22%7D%7D%2C%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F41768106-6076-482d-821b-a7d197d6adbc%22%7D%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F41768106-6076-482d-821b-a7d197d6adbc%22%7D%7D%7D%5D%7D%5D%7D&facetRequest=true)
[Furniture](https://lux.collections.yale.edu/view/object/070f65b6-849d-4c6f-a7ff-1d4a87384f47)
[Photographs](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22o%27keeffe%22%2C%22_lang%22%3A%22en%22%7D&sq=o%27keeffe&ip=1&facetRequest=true&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2Ff391b71c-208e-46eb-8701-ad9cf965fd62%22%7D%7D%5D%7D)

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

**Dependencies/Blocks:**

- Blocking: https://github.com/project-lux/lux-frontend/issues/40

**Related Github Issues:**

**Related links:**

**Wireframe/Mockup:**

**Comment by prowns** [comment] 2024-02-29 21:37
@clarkepeterf - can you clarify which new data constants are needed?

**Comment by prowns** [comment] 2024-03-04 13:11
@clarkepeterf  - is this a dupe of #55

**Comment by ar2674** [comment] 2024-03-04 14:43
closing this tix as I have added it's information into #55

**Closed by ar2674** 2024-03-04 14:43 UTC

**Comment by prowns** [comment] 2024-03-12 19:12
Dupe of #55 - closed
