### ISSUE TITLE
Create Search Terms For Creation/Production Influenced By Agent

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#65] opened 2024-03-06 19:15 UTC
**Problem Description:**
The frontend would like to display Objects whose production was influenced by a person:
https://github.com/project-lux/lux-frontend/issues/87
https://github.com/project-lux/lux-middletier/issues/27

**Expected Behavior/Solution:**
Create a new Index and JSON Search Term that allows to search for objects whose creation or production were influenced by a person

**Requirements:**
The answer to the following is YES.
> @azaroth42  @kkdavis14 do we want a search term in each direction? E.g.:
>     a. search for Objects that were influenced by this Person
>     b. search for People that influenced this Object? If so, we will want to add a triple called something like `lux:agentOfInfluence`

New Triples:
`lux:agentInfluencedCreation`
`lux:agentInfluencedProduction`

List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
- [x] Questions
  - [x] From above -  Do we want a search term in each direction? E.g.:
    a. search for Objects that were influenced by this Person
    b. search for People that influenced this Object? If so, we will want to add a triple called something like `lux:agentOfInfluence`

**UAT/LUX Examples:**
- See FE or MT issue. 

**Dependencies/Blocks:**

~~- Blocked By: Issues that are blocking the completion of the current issue.~~
- Blocking: https://github.com/project-lux/lux-middletier/issues/27
- Blocked: Per team meeting we need a new Triple for this (https://github.com/project-lux/data-pipeline/issues/19)

**Related Github Issues:**

- https://github.com/project-lux/lux-frontend/issues/87

**Related links:**

 - https://www.bugherd.com/projects/284041/tasks/1943

**Wireframe/Mockup:**
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by kkdavis14** [comment] 2024-03-06 20:25
I think we want search in both directions, and tentatively think we should combine it on the Person page into the "Objects Created...By" tab, as as Peter mentioned in Teams, a triple something like "lux:agentOfInfluenceOrProduction".

Tentatively because I'm not sure if we should combine them or add a separate tab on People page for Attributions like this.

**Comment by clarkepeterf** [comment] 2024-03-06 21:02
@prowns #agenda

**Comment by prowns** [comment] 2024-03-27 14:58
Per 3/7/24 Team meeting: @azaroth42 will add a new Triple for this

**Comment by clarkepeterf** [comment] 2024-05-07 19:33
Blocked by pipeline issue, but done forming. Moving to prioritization review

**Comment by roamye** [comment] 2024-05-13 15:49
I believe this new triple will require two HAL link test cases. 

1. lux:agentInfluencedCreation
2. lux:agentInfluencedProduction

I added it to the LUX TEST cases - Additions spreadsheet, once a search-will-match url is created I can add the test case to the regression test.

**Comment by roamye** [comment] 2024-06-13 20:27
The pipeline issue is no longer blocking this as it was closed on May 9th. 

@clarkepeterf

**Comment by roamye** [comment] 2024-06-26 19:46
Approved by UAT

**Comment by roamye** [comment] 2024-07-01 20:25
Looks good in prod. Closing.

**Closed by roamye** 2024-07-01 20:25 UTC
Labels: normal, Ready to Deploy, To Be Deployed
