### ISSUE TITLE
Unable to search by Yale identifiers, such as ils:yul:mfhd:8752038, unless quoted (or in advanced search)

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-marklogic#272] opened 2024-08-05 20:08 UTC
> [!NOTE]
> This ticket slightly overlaps with project-lux/lux-middletier#93.  Rob is interested in both but prioritizes this ticket over project-lux/lux-middletier#93.

**Problem Description:**
A production log check surfaced the system failing to perform a keyword search on an ID:

```
2024-08-04 18:55:05.987 Notice: JS-JAVASCRIPT: throw new BadRequestError( -- Error running JavaScript request: Error: Unable to parse the search criteria: ils:yul:mfhd:8752038
2024-08-04 18:55:05.987 Notice:+in ../../lib/SearchCriteriaProcessor.mjs, at 9:5, in translateStringGrammarToJSON() [javascript]
2024-08-04 18:55:05.987 Notice:+in ../../lib/SearchCriteriaProcessor.mjs, at 798:24, in translateStringGrammarToJSON() [javascript]
2024-08-04 18:55:05.988 Warning: {"errorResponse":{"statusCode":400,"status":"Bad Request","messageCode":"BadRequestError","message":"Unable to parse the search criteria: ils:yul:mfhd:8752038"}}
```

Indeed, performing a simple search on unquoted string that contains at least two colons (without whitespace) into `cts.parse` results in an error: XDMP-UNEXPECTED: cts.parse('ils:yul:mfhd') -- Unexpected token syntax error, unexpected NameColon_

In this case, the user was trying to search by a known ID for https://lux.collections.yale.edu/view/object/5010d875-9095-4de7-a92e-32cb20e56453.  

**Expected Behavior/Solution:**
Workaround: quote the string in simple search or switch to advanced search.

If we do not want to require the user to quote the string, we could edit modify `translateStringGrammarToJSON` to auto-quote terms that contain two or more colons.

**Requirements**
From UAT 8/26 - it was decided to go with the option of: auto-quoting search terms which do not have spaces. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- https://lux.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22ils%3Ayul%3Amfhd%3A8752038%22%2C%22_stemmed%22%3Afalse%2C%22_lang%22%3A%22en%22%7D&sq=%22ils%3Ayul%3Amfhd%3A8752038%22 will return the same amount as below & be auto quoted. 
- https://lux.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22ils%3Ayul%3Amfhd%3A8752038%22%2C%22_stemmed%22%3Afalse%2C%22_lang%22%3A%22en%22%7D&sq=%22ils%3Ayul%3Amfhd%3A8752038%22 

**Dependencies/Blocks:**

N/A

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**

N/A

**Wireframe/Mockup:**
N/A

**Comment by clarkepeterf** [comment] 2024-08-16 00:02
@azaroth42 based on [this comment](https://github.com/project-lux/lux-marklogic/issues/29#issuecomment-2276069021) do we want to add a workaround for this in our ML code? A string with 2 or more colons breaks `cts.parse`, but we can look for terms with 2 or more colons and quote them

**Comment by jffcamp** [comment] 2024-08-22 14:13
Do we understand the impact of the second option? "If we do not want to require the user to quote the string, we could edit modify translateStringGrammarToJSON to auto-quote terms that contain two or more colons."

**Comment by brent-hartwig** [comment] 2024-08-22 14:47
@jffcamp, there would be no noticeable performance impact as we are already parsing the user-provided string.  This would be a tweak to that logic: if a term (contiguous string of non-whitespace characters) includes two colons, add quotes.  If you're asking about possible negative side effects, none come to mind at this time.  The level of effort is low and it would be easy to back the change out --very isolated and in code that is only used to convert from the string search grammar to the JSON search grammar.

**Comment by prowns** [comment] 2024-08-22 15:56
Per UAT - non-issue?  Works with quotations and in adv. search

https://lux.collections.yale.edu/view/results/objects?q=%7B%22identifier%22%3A%22ils%3Ayul%3Amfhd%3A8752038%22%7D
OR
https://lux.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22ils%3Ayul%3Amfhd%3A8752038%22%2C%22_options%22%3A%5B%22punctuation-sensitive%22%2C%22unstemmed%22%2C%22unwildcarded%22%5D%7D%5D%7D

@brent-hartwig - Is there a search tag validation that could be causing the problem?

**Comment by brent-hartwig** [comment] 2024-08-22 16:50
@prowns, this issue is limited to simple search.  Advanced search doesn't go through `cts.parse`, which is the function that isn't happy with the double-colons.  Apologies for not clearly stating that.

![image](https://github.com/user-attachments/assets/8de39fe3-a4ff-48a5-803a-f87c43729a90)

**Comment by roamye** [comment] 2024-08-26 17:18
From 8/26 UAT: 

Can we default any string which does not have spaces to be quoted? So for example, when a user searches for ils:yul:mfhd:8752038 it will be updated to "ils:yul:mfhd:8752038" so it can return the correct results. (Link Below)  

https://lux.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22ils%3Ayul%3Amfhd%3A8752038%22%2C%22_stemmed%22%3Afalse%2C%22_lang%22%3A%22en%22%7D&sq=%22ils%3Ayul%3Amfhd%3A8752038%22

**Comment by brent-hartwig** [comment] 2024-08-26 17:21
I'd expect that would be just fine.

**Comment by roamye** [comment] 2024-11-19 14:57
Please note per this comment: https://github.com/project-lux/lux-marklogic/issues/272#issuecomment-2310689833 
the search of `ils:yul:mfhd:8752038` is supposed to 
1) show the same results as `"ils:yul:mfhd:8752038"` but also 
2) auto-change the text to revert from `ils:yul:mfhd:8752038` to `"ils:yul:mfhd:8752038"`

While it does 1) it does not do 2). Is this something that can be a hot-fix or would it need to be moved to the next milestone to make the change?  Is there a reason it should no longer be auto-quoted? 

@clarkepeterf @brent-hartwig

**Comment by brent-hartwig** [comment] 2024-11-19 17:24
@clarkepeterf, please see PR https://github.com/project-lux/lux-marklogic/pull/378.  If you like it, I'll leave it to your git-fu to it into 1.29.  I used temporary log statements to compare the before and after.  The < and > characters denote the beginning and ending of the criteria.

```
2024-11-19 17:04:15.815 Info: Before: <ils:yul:mfhd and map>
2024-11-19 17:04:15.815 Info:  After: <"ils:yul:mfhd" AND map>
```

Before merging the PR, let's wait to hear back from Amy on --if I'm understanding correctly-- having the frontend display the modified criteria.

> Can we default any string which does not have spaces to be quoted?

@roamye, once in the code I realized this is probably more trouble (and error prone) than worth it.  The underlying issue is that the colon character is an operator in MarkLogic's string search grammar.  You can see its uses [here](https://docs.marklogic.com/guide/search-dev/string-query#id_98389).  The modified implementation is limited to the colon character.  Unless we discover another scenario that necessitates auto quoting, I recommend limiting the implementation to the colon character.

**Comment by clarkepeterf** [comment] 2024-11-19 19:53
@brent-hartwig I'm fine with either implementation. I think the original one is fine because operators require other adjacent terms. E.g. `AND` needs something like `andy AND warhol`

@roamye Are you sure it needs to show as quoted in the UI? I think "auto-quote" was really meant to be part of the internal implementation, not something that is exposed to the user. (So we probably shouldn't have mentioned quoting since that would not be part of the user-facing change)

**Comment by brent-hartwig** [comment] 2024-11-19 19:59
I'm not following you, @clarkepeterf.  As soon as the user enters more than one term in the simple search box, the original implementation of this ticket no longer applies --whether that be `term1 term2` or `term1 [operator] term2`.

**Comment by clarkepeterf** [comment] 2024-11-19 20:02
@brent-hartwig exactly.  Apologies, I was responding to a comment in the code which I was interpreting as a comment about the original implementation, but is in fact only relevant to the updated code

**Comment by clarkepeterf** [comment] 2024-11-19 20:09
@roamye @brent-hartwig

Confirmed in Yale Teams that we should leave the UI as is. No need to add quotes in the frontend.

I will test Brent's changes and assuming those look good I will push those

**Comment by roamye** [comment] 2024-11-21 21:26
Approved by UAT

**Comment by roamye** [comment] 2024-11-26 15:15
Looks good in PROD. Closing.

**Closed by roamye** 2024-11-26 15:15 UTC
Labels: Awaiting Review, important, search
