### ISSUE TITLE
Research: Related lists are displaying search results that do not belong. 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-marklogic#233] opened 2024-07-17 15:43 UTC
**Problem Description:**
Accordion `Related People and Groups` show concepts such as `Exhibitions` and `Travel` that should not appear within the accordion. It also has labels such as "Influenced Creation this Person" which does not make sense. 

The concepts above also do not show within the Related Concepts accordion.  

From TF 7/16, this is an issue with the related list and this ticket will serve as a research issue to further investigate the related list. 

**Expected Behavior/Solution:**
TBD based on research. 

**Requirements:**
TBD

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

-  https://lux-front-tst.collections.yale.edu/view/person/165a61ff-8455-4a04-9505-bb8e37a149c3 (related ppl & groups) 

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2379

~**Wireframe/Mockup:**~
~Place wireframe/mockup for the proposed solution at end of ticket.~

**Comment by brent-hartwig** [comment] 2024-07-25 14:59
Analysis: The `creationInfluencedBy` and `productionInfluencedBy` search terms were added to the agent (people and groups) search scope in release1.19, which is the first time the `created-creationInfluencedBy` relation appeared within the agent-to-agent related list configuration.  The same is true for the `produced-productionInfluencedBy` relation.  The cause is an invalid target scope of the `creationInfluencedBy` and `productionInfluencedBy` search terms: they are agent when the should be concept.  Fixing in release1.22.

**Comment by clarkepeterf** [comment] 2024-07-25 16:18
@brent-hartwig agents were the intended target scope for `creationInfluencedBy` and `productionInfluencedBy`. This change was specified in #65. They can produce valid results. Examples:
- [productionInfluencedBy results](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22productionInfluencedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fperson%2F0573429b-32ef-4a42-99e6-fd4b382d7e8e%22%7D%7D%5D%7D)
- [creationInfluencedBy results](https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22creationInfluencedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fperson%2Ff07509c5-2716-40b0-99ac-6b1ab5dc4fff%22%7D%7D%5D%7D)

Perhaps there are some concepts that get linked through the same triples in the data?

**Comment by brent-hartwig** [comment] 2024-07-25 16:20
@clarkepeterf, perhaps.  But could also be completely unrelated to #65.

**Comment by brent-hartwig** [comment] 2024-07-25 17:06
@clarkepeterf and @roamye, I'm going to set this aside.  I set out to briefly investigate, thought it was a quick fix, then got sucked into a vortex.  Since its status was Forming, I have no business spending more time on it now.

**Comment by roamye** [comment] 2024-07-25 18:50
@brent-hartwig thanks for the initial investigation!

Is it correct to assume @clarkepeterf will continue where you left off? or will this ticket be further researched by both of you when other higher priority tickets have been complete? 

(not an urgent question/issue, just curious)

**Comment by brent-hartwig** [comment] 2024-07-25 19:10
Yes, with Peter until/unless I am asked.  Thanks.

**Comment by clarkepeterf** [comment] 2024-08-02 10:12
@kkdavis14  @azaroth42 I think there are some misplaced `lux:agentInfluencedCreation` triples in the data.

For example, [this Concept document](https://lux.collections.yale.edu/data/concept/b2ede86c-7929-4168-a7b8-bd282b0ed912) has the following triples:
```
{
"subject": "https://lux.collections.yale.edu/data/concept/b2ede86c-7929-4168-a7b8-bd282b0ed912", 
"predicate": "https://lux.collections.yale.edu/ns/agentInfluencedCreation", 
"object": "https://lux.collections.yale.edu/data/person/165a61ff-8455-4a04-9505-bb8e37a149c3"
}
```
``` 
{
"subject": "https://lux.collections.yale.edu/data/concept/b2ede86c-7929-4168-a7b8-bd282b0ed912", 
"predicate": "https://lux.collections.yale.edu/ns/agentInfluencedCreation", 
"object": "https://lux.collections.yale.edu/data/concept/86e2cdb0-e84a-46fe-89cd-fb344228f359"
}
```

This seems strange to me because:
1. I would expect that the subject of`lux:agentInfluencedCreation` triples would always be a Work
2. I would expect that the object of `lux:agentInfluencedCreation` triples would always be an Agent

In this case, the subject for both is a Concept, and the object for one of them is also a Concept.


This is why the 'exhibitions' Concept shows up as a Related Person/Group on the Pablo Picasso page. Because they  both influence the concept [Picasso, Pablo, 1881-1973--Exhibitions](https://lux.collections.yale.edu/data/concept/b2ede86c-7929-4168-a7b8-bd282b0ed912), as well as 45 other concepts that have both of them as component terms. And then the link to show the Works they both influence returns 0 results, because none of the things they both influenced are actually a Work, they are all concepts.

**Comment by azaroth42** [comment] 2024-08-02 19:00
Yes, a bug for sure. 
@kkdavis14 Look in marklogic/mapper.py, the block at line 234 that we were fixing yesterday for `caused_by`. At the very least it would need to test for agent-ness, but might need stronger logic / constraints.

**Comment by clarkepeterf** [comment] 2024-08-02 20:45
Thanks @kkdavis14 and @azaroth42

@roamye Research is done. Kelly and Rob have created an issue in the pipeline repo: https://github.com/project-lux/data-pipeline/issues/112. I think this ticket can be closed. I will put into Reviewable in case you want any other action taken before closing

**Closed** 2024-08-07 15:05 UTC
Labels: related lists, blocking
